#ifndef BATTLESHIPS_H
#define BATTLESHIPS_H

///////////////////////////////////////////////////////////////////////////////
// include API headers for all classes so that single include file is sufficient

#include <battleships/Exports.H>
#include <battleships/BattleShips.H>
#include <battleships/Board.H>
#include <battleships/Game.H>
#include <battleships/PrimaryBoard.H>
#include <battleships/TrackingBoard.H>
#include <battleships/Validator.H>

///////////////////////////////////////////////////////////////////////////////

#endif /* BATTLESHIPS_H */